# Streamlit Secrets Configuration
# This file should be used in production to store sensitive information
# For local development, use environment variables

# OpenAI API Configuration
# OPENAI_API_KEY = "your-api-key-here"

# Other configuration options can be added here